### PR TITLE
Added median household income spec for two methods

### PR DESCRIPTION
**Pull request by sekharp**
Two methods for the median household income CSV. Pretty straightforward, followed style of methods asked for beforehand

### CODE REVIEW

**Comment by sekharp** [comment]
We <3 influence points

**Comment by sekharp** [comment]
Can someone do the PR on the test harness for us

**Comment by amcrawford** [comment]
+1

**Comment by stevekinney** [comment]
I'm going to close this because it's now conflicted with the current version that @tessgriffin updated. That said, if you want to resolve the conflicts, go ahead and reopen this pull request and I'll happily merge it.

**Pull request closed without merging**
