### PR TITLE
Swapped `UnknownDataError` for `UnknownRaceError`

### PR DESCRIPTION
**Pull request by emilydowdle**
Corrected `UnknownDataError` in .proficient_by_race_or_ethnicity(race)

### CODE REVIEW

**Comment by JoshCheek** [comment]
Can you send PR on https://github.com/turingschool-examples/headcount_test_harness as well, and get some consensus +1s on this ^_^  (note: whoever you get to +1 this, you could let them do the PR for the test harness, then you both get an influence point!)

**Comment by amcrawford** [comment]
This sounds good to me!

**Comment by sekharp** [comment]
+1

**Comment by acareaga** [comment]
+1

**Comment by sekharp** [comment]
Did the PR josh requested on the test harness so it reflects the same race error instead of data error for the same method in statewide testing https://github.com/turingschool-examples/headcount_test_harness/pull/9

**Pull request merged**
